# Generated by Django 4.2.7 on 2024-01-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nisa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatid', models.CharField(max_length=200, null=True)),
                ('nama', models.CharField(max_length=200, null=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Kontak',
            },
        ),
        migrations.AlterField(
            model_name='produk',
            name='aktif',
            field=models.BooleanField(default=False),
        ),
    ]
